# Generated by Django 2.1.5 on 2019-04-02 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersLobby', '0002_userslobby_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslobby',
            name='photo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
