# Generated by Django 2.1.5 on 2019-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='deleted',
            field=models.IntegerField(null=True),
        ),
    ]
